# Serverless Compose Configuration
# Gestiona múltiples microservicios de AlertaUTEC

services:
  # Microservicio de Autenticación
  # Responsabilidad: Gestión de usuarios y tokens
  autenticacion:
    path: microservicio-autenticacion
    params:
      stage: ${opt:stage, 'dev'}
      region: us-east-1

  # Microservicio de Reportes
  # Responsabilidad: Gestión CRUD de reportes e incidentes
  reportes:
    path: microservicio-reportes
    params:
      stage: ${opt:stage, 'dev'}
      region: us-east-1

  # Microservicio de Notificaciones en Tiempo Real
  # Responsabilidad: Comunicación por WebSockets
  # Depende de reportes porque consume su stream de DynamoDB
  notificaciones:
    path: microservicio-notificaciones
    params:
      stage: ${opt:stage, 'dev'}
      region: us-east-1
    dependsOn:
      - reportes

  # Microservicio de Analítica
  # Responsabilidad: Análisis de datos, ingesta y consultas
  # Depende de reportes porque necesita las tablas DynamoDB creadas
  analitica:
    path: microservicio-analitica
    params:
      stage: ${opt:stage, 'dev'}
      region: us-east-1
    dependsOn:
      - reportes
